stages:
  - test
  - build
  - deploy
  - announce

test:
  image: node:12.13-alpine
  stage: test
  variables:
    DB_CONNECTION_TEST: "mongodb://localhost:27018"
  services:
    - mongo:latest
  script:
    - npm install
    - npm test
  only:
    - development
    - master

deploy:
  image: ruby:2.5.6
  stage: deploy
  script:
    - apt-get update -q
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APPNAME --api-key=$HEROKU_APIKEY
  only:
    - development

build-image-to-production:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.gitlab.com
    - docker build -t $DOCKER_IMAGE_NAME:stable .
    - docker push $DOCKER_IMAGE_NAME:stable
  only:
    - master

deploy-to-production:
  stage: deploy
  script:
    - 'which ssh-agent || (apt-get update && apt-get install ssh-agent -y)'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ssh root@134.209.105.240 bash --login "./app/backend/deploy.sh"
  only:
    - master

announce:
  stage: announce
  script:
    - curl --data chat_id=$TELEGRAM_CHAT_ID --data-urlencode text="[$CI_PROJECT_NAME - $CI_COMMIT_REF_NAME] $CI_COMMIT_TITLE by $GITLAB_USER_NAME" $TELEGRAM_BOT_URL/sendMessage
