version: "3"
services:
  awesome-movie-database:
    image: registry.gitlab.com/ellvisca/awesome-movie-database:stable
    container_name: "awesome-movie-database"
    network_mode: "host"
    environment:
      - JWT_SIGNATURE_KEY='SECRET'
      - NODE_ENV=production
      - publicKey=public_5Hn55wwzH48M+rVl/7am9e6xqy0=
      - privateKey=private_i2qRf3R8NLPJkAUPb1gxGRT52Ak=
      - urlEndpoint=https://ik.imagekit.io/m1ke1magek1t
    ports:
      - "8000:8000"
